version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lights_and_sounds
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server

  website:
    build: .
    command: sh -c "RAILS_MASTER_KEY=25ebe25959cfe7f7e061b50405c48226 DISABLE_DATABASE_ENVIRONMENT_CHECK=1 rails db:setup && RAILS_ENV=production RAILS_LOG_TO_STDOUT=true bundle exec rake assets:precompile && foreman start"
    depends_on:
      - 'postgres'
      - 'redis'
      # - 'sidekiq'
    ports:
      - "80:80"

  # sidekiq:
  #   depends_on:
  #     - 'postgres'
  #     - 'redis'
  #   build: .
  #   command: sh -c "RAILS_MASTER_KEY=25ebe25959cfe7f7e061b50405c48226 bundle exec sidekiq"
