version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    environment:
      - POSTGRES_USER:'postgres'
      - POSTGRES_PASSWORD:'postgres'
      - POSTGRES_DB:'lights_and_sounds'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server

  website:
    build: .
    command: bundle exec rails s -p 80 -b '0.0.0.0'
    depends_on:
      - 'postgres'
      - 'redis'
      - 'sidekiq'
    ports:
      - "80:80"

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bundle exec sidekiq
